import Head from "next/head";

import styles from "@/styles/Home.module.css";
import RootLayout from "@/components/RootLayout/RootLayout";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faHandshake,
  faRectangleList,
} from "@fortawesome/free-regular-svg-icons";
import { Button } from "react-bootstrap";
import { faScaleBalanced } from "@fortawesome/free-solid-svg-icons";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <RootLayout>
        <div className={`${styles.banner} row no-gutters shadow`}>
          <div
            className={`${styles["left-banner"]} col-md-auto p-0 h-100 position-relative`}
          >
            <div className={`${styles["text-banner"]} position-absolute`}>
              <h3>Có thể với bạn là điều nhỏ nhoi......</h3>
              <p>
                "Chúng tôi cùng với bạn, trên hành trình tìm hạnh phúc, bằng
                cách lan tỏa lòng nhân ái, chuyển hóa nổi đau."
              </p>
            </div>
            <div className={`position-absolute  ${styles["actions-banner"]}`}>
              <Button
                type="button"
                variant="success"
                className="d-flex gap-2 mb-2 align-items-center justify-content-center"
              >
                <FontAwesomeIcon width={24} icon={faRectangleList} />
                <h4 className="m-0 h5">Kiểm tra đóng góp</h4>
              </Button>
              <Button
                type="button"
                variant="success"
                className="d-flex gap-2 mb-2 align-items-center justify-content-center"
              >
                <FontAwesomeIcon width={24} icon={faHandshake} />
                <h4 className="m-0 h5">Hợp tác</h4>
              </Button>
              <Button
                type="button"
                variant="success"
                className="d-flex gap-2 align-items-center justify-content-center"
              >
                <FontAwesomeIcon width={24} icon={faScaleBalanced} />
                <h4 className="m-0 h5">Quy tắc</h4>
              </Button>
            </div>
            <div className={`${styles["layer-1"]} h-100`}>
              <div className={styles["layer-2"]}></div>
            </div>
          </div>
          <div className={`${styles["right-banner"]} p-0 col h-100`}>
            <div className={styles["backdrop-pseudo"]}></div>
            <div className={styles["backdrop-pseudo2"]}></div>
            <div className={styles["layer-1"]}>
              <div className={`${styles["layer-2"]} h-100`}>
                <div className={`${styles["layer-4"]} w-100 h-100`}>
                  <div className={`${styles["layer-3"]} w-100 h-100`}></div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className={`${styles["short-intro"]} row`}>
          <div
            className={`col d-flex flex-column align-items-center justify-content-center`}
          >
            <div className={`${styles["container"]}`}>
              <h3 style={{ color: "#005a5b" }}>
                Nền tảng quyên góp từ thiện cây xanh
              </h3>
              <p>
                Cây xanh là nền tảng giúp bạn dễ dàng chung tay quyên góp tiền
                cùng hàng triệu người, giúp đỡ các hoàn cảnh khó khăn trên khắp
                cả nước.
              </p>
              <div className={`row ${styles.statistics} mb-3`}>
                <div className={`${styles["statistics-el"]} col`}>
                  <h5>423</h5>
                  <span>Dự án được gây quỹ thành công</span>
                </div>
                <div className={`${styles["statistics-el"]} col`}>
                  <h5>35+ tỷ</h5>
                  <span>đồng được quyên góp</span>
                </div>
                <div className={`${styles["statistics-el"]} col`}>
                  <h5>8+ triệu</h5>
                  <span>lượt quyên góp</span>
                </div>
              </div>
              <div className="d-flex gap-2">
                <Button type="button" variant="success">
                  Quyên góp
                </Button>
                <Button type="button" variant="outline-success">
                  Giới thiệu
                </Button>
              </div>
            </div>
          </div>
          <div
            className={`col-md-5 p-0 d-flex align-items-center justify-content-center `}
          >
            <Image
              src="/5474102.jpg"
              width={400}
              height={400}
              style={{ borderRadius: "0.5rem" }}
              alt="masf"
            />
          </div>
        </div>
        <div className={`${styles["exemplary-projects"]} position-relative`}>
          <div className={`${styles.title} shadow position-absolute`}>
            <h3>Exemplary projects</h3>
          </div>
          <div className={`${styles.content} shadow row`}>
            <div className={`col ${styles["img-container"]} shadow m-4`}>
              <img
                src="/san_choi_tre_em_khiem_thi/momo-upload-api-230411143104-638168202647105383.jpg"
                alt="fsa"
              />
              <div className={styles["nav-img"]}>
                <div
                  className={`${styles["nav-img-el"]} ${styles["img-active"]}`}
                ></div>
                <div className={styles["nav-img-el"]}></div>
                <div className={styles["nav-img-el"]}></div>
                <div className={styles["nav-img-el"]}></div>
              </div>
            </div>
            <div className={`col p-4`}>
              <div className={styles["text"]}>
                <h3>
                  Chung tay xây dựng sân chơi cho các em nhỏ khiếm thị tại Trung
                  tâm trẻ em khiếm thị Tây Ninh
                </h3>
                <h5>27/03/2023</h5>
                <p>
                  ❤️ Tăng cường sức khỏe thể chất và tinh thần cho trẻ em khiếm
                  thị tại trung tâm trẻ em khiếm thị Tây Ninh thông qua việc
                  kiến tạo sân chơi hòa nhập
                </p>
                <div className="d-flex gap-2">
                  <Button type="button" variant="success">
                    Quyên góp
                  </Button>
                  <Button type="button" variant="outline-success">
                    Chi tiết
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </RootLayout>
    </>
  );
}
